name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake (if needed)
        run: sudo apt-get update && sudo apt-get install -y cmake


      - name: Build and run tests
        run: |
          cd Laboratorios/Laboratorio08/src/
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Se ejecutan las pruebas, listas para el deployment."
